# Generated by Django 5.2.4 on 2025-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_add_slug_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notablog',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
