# Generated by Django 5.2.4 on 2025-08-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
